#!/usr/bin/env bash

NODE=$(which node)
NODE_VERSION=$($NODE -v)
NODE_VERSION=$(echo ${NODE_VERSION#*v} | cut -d. -f1)

FLAGS=""
LIB_DIR="lib/lts"
if [ "$NODE_VERSION" -gt "6" ]; then
	FLAGS="--harmony-async-await"
	LIB_DIR="lib/node7"
fi

export ORIGINAL_WD=$(pwd)
cd "`dirname "$BASH_SOURCE"`/$LIB_DIR"

exec $NODE boot/Cli.js "$@"
